[advisories]
ignore = []

[licenses]
allow = [
    "Apache-2.0",
    "MIT",
]
confidence-threshold = 0.8

[bans]
# Lint level for when multiple versions of the same crate are detected
multiple-versions = "warn"
highlight = "lowest-version"
allow = [
]
deny = [
]

# Certain crates/versions that will be skipped when doing duplicate detection.
skip = [
]
skip-tree = [
    # This is useful for dev-dependencies like criterion which often pin their own versions of rand
]
